HOCS-2424 Add temporary timestamp logging for extract
UKHomeOffice/hocs-audit pull request #76
Opened 2021-02-04 15:58 UTC by ARobinsonHOD

- Add additional (temporary) logging to track changes to timestamp on case extract to help find bug in prod

2021-02-05 10:10 UTC, LiamMacP requested changes
Good choice to use `log.info` - as that ensures it shows in production (debug logs are hidden in production builds. 

The logging does seem a little over the top - maybe isolate the testing to just the ZonedDateTimeConverter on a before and after.

2021-02-05 13:23 UTC, LiamMacP approved these changes

2021-02-05 13:25 UTC, LiamMacP approved these changes

2021-02-05 13:30 UTC, LiamMacP commented on src/main/java/uk/gov/digital/ho/hocs/audit/application/ZonedDateTimeConverter.java
> +        log.info("Timestamp before convert: {}", localDateTime);
Logger is not valid in this case - you will need to add the annotation to the top of this file to use Lomboks.

2021-02-05 13:41 UTC, LiamMacP commented on src/main/java/uk/gov/digital/ho/hocs/audit/application/ZonedDateTimeConverter.java
> +        log.info("Timestamp before convert: {}", localDateTime);
Build passing now, resolved.

2021-02-05 13:41 UTC, LiamMacP approved these changes

2021-02-09 12:22 UTC, Paulcr-ho approved these changes

2021-02-09 14:06 UTC, merged